name: scipygeo18
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas
  - geoplot
  - pysal
  - folium
  - scikit-learn
  - rasterio
  - pip
  - pip:
    - contextily
    - libpysal
    - mgwr
    - mapclassify
    - esda
